### ISSUE TITLE
[TODO] 교내 SNS 모음

### ISSUE THREAD

**Issue by dlguswn3659** [korECM/CAUFingerPrincess#5]
**할 일**

- [ ] 각 단과대 별로 카드 나누기(서울 + 안성)

- [ ] 각 학과별 SNS 카드 분배하기

- [ ] 총학(서울, 안성), 통합커뮤니티, 대숲, 동아리 연합회 

- [ ] 기타 SNS (학교 축제, 다빈치 SW 교육원, 중앙사랑, 카운슬러 등)

**설명**

단과대 학생회에서 주관하는 행사 등의 공지사항은 SNS를 통해 올라오기 때문에, SNS를 하지 않는 사람들도 해당 정보 접근이 가능할 필요가 있음
