### ISSUE TITLE
[TODO] 교내학칙

### ISSUE THREAD

**Issue by dlguswn3659** [korECM/CAUFingerPrincess#6]
**할 일**

- [ ] 중앙대학교 학칙(링크)

- [ ] 동아리 회칙(링크)

- [ ] 장학금 제도(라우터 페이지)

- [ ] 기숙사 규정(라우터 페이지)
0. 기숙사 공지사항 
      - 공통안내사항(http://dormitory.cau.ac.kr/bbs/notice03.php) 
     - 블루미르홀 공지사항(http://dormitory.cau.ac.kr/bbs/bbs_list.php?bbsID=notice) 
     - 퓨처하우스 공지사항(http://dormitory.cau.ac.kr/bbs/bbs_list.php?bbsID=notice2) 
     - 글로벌하우스 공지사항(http://dormitory.cau.ac.kr/bbs/bbs_list.php?bbsID=notice3) 
1. 생활관규정 (http://dormitory.cau.ac.kr/guide/regulation.php) 
2. 운영세칙 (http://dormitory.cau.ac.kr/guide/regulation.php) 
3. 관생수칙 (http://dormitory.cau.ac.kr/guide/regulation.php)

**설명**
